server:
#  port: 8090
  servlet:
    contextPath: /petproject

spring:
  application:
    name: petproject
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: pet
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    schema: classpath:/db/schema-postgres.sql
    initialization-mode: always

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    default-schema: pet
    parameters:
      schema: pet
      own: postgres

